---
title: "Untitled"
author: "Miguel Angel Peñaloza Perez"
date: "17/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(agricolae)
library(kableExtra)
library(dplyr)
# Statistical procedures for agricultural research, pag 143
# Grain Yields of Three Rice Varieties Grown under 
#Three Management practices and Five Nitrogen levels; in a
#split-split-plot design with nitrogen as main-plot, 
#management practice as subplot, and variety as sub-subplot 
#factores, with three replications.
library(agricolae)
data<-read.csv("C:\\Users\\W10\\Desktop\\PROYECTO EQUIPO\\ANALISIS_TEMPE.csv",header=TRUE)
model<-with(data,ssp.plot(REPETICION,ZONA,TIEMPO,TRATAMIENTO,GRADOS_FAREN))
gla<-model$gl.a; glb<-model$gl.b; glc<-model$gl.c
Ea<-model$Ea; Eb<-model$Eb; Ec<-model$Ec
op<-par(mfrow=c(1,3),cex=0.6)
out1<-with(data,LSD.test(GRADOS_FAREN,ZONA,gla,Ea,console=TRUE))
out2<-with(data,LSD.test(GRADOS_FAREN,TIEMPO,glb,Eb,console=TRUE))
out3<-with(data,LSD.test(GRADOS_FAREN,TRATAMIENTO,glc,Ec,console=TRUE))
plot(out1,xlab="ZONA",las=1,variation="IQR")
plot(out2,xlab="TIEMPO",variation="IQR")
plot(out3,xlab="TRATAMIENTO",variation="IQR")
# with aov
AOV<-aov(GRADOS_FAREN ~  REPETICION + ZONA*TIEMPO*TRATAMIENTO + Error(REPETICION/ZONA/TIEMPO),data=data)
summary(AOV)
par(op)
kable(model$ANOVA)
#kable(model$)

AOV$REPETICION
AOV$`REPETICION:ZONA`
AOV$`REPETICION:ZONA:TIEMPO`
AOV$Within
AOV$`(Intercept)`


#data%>% group_by(ZONA,TIEMPO)%>%get_summary_stats(GRADOS_FAREN,type="mean_sd")




```

```{r}
library(emmeans)
library(rstatix)
library(dplyr)
#data%>% group_by(ZONA,TIEMPO)%>%get_summary_stats(GRADOS_FAREN,type="mean_sd")

#data %>% group_by(TIEMPO)
#emmeans_test (GRADOS_FAREN~TIEMPO,p.adjust.method = "bonferroni")

A<-data %>% group_by(ZONA)%>%
emmeans_test(GRADOS_FAREN~TIEMPO,p.adjust.method = "bonferroni")

A
A<-dplyr::select(A,ZONA,group1,group2,p  ,p.adj,p.adj.signif)
A<-kable(A)


B<-data %>% group_by(ZONA)%>%
emmeans_test(GRADOS_FAREN~TIEMPO,p.adjust.method = "bonferroni")
B
B<-dplyr::select(B,ZONA,group1,group2,p,p.adj,p.adj.signif)
kable(B)

C<-data %>% group_by(ZONA)%>%
emmeans_test(GRADOS_FAREN~TRATAMIENTO,p.adjust.method = "bonferroni")
C
C<-dplyr::select(C,ZONA,group1,group2,p,p.adj,p.adj.signif)
kable(C)

D<-data %>% group_by(TIEMPO)%>%
emmeans_test(GRADOS_FAREN~TRATAMIENTO,p.adjust.method = "bonferroni")
D
D<-dplyr::select(D,TIEMPO,group1,group2,p,p.adj,p.adj.signif)
kable(D)

#kable(D)


E<-data %>% group_by(ZONA,TIEMPO)%>%
emmeans_test(GRADOS_FAREN~TRATAMIENTO,p.adjust.method = "bonferroni")
E

E<-dplyr::select(E,TIEMPO,ZONA,group2,group1,p,p.adj,p.adj.signif)
kable(E)

```






